### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by sobti619** [chris-lovejoy/geetle#37]
**Info Pop Up**
- Info pop up text needs to be all center justified.
- The line "two modes of play" should be on a separate line as a new paragraph above the mode titles
- Underline mode titles
- Pop up needs to fit on one screen on mobile view. Also 'Welcome to Geetle' seems to disappear sometimes.
- Masti and Ustaad button colours should be the same as the assigned colours in the rest of the site. The teal and pink/purple.
![image](https://user-images.githubusercontent.com/114086037/193406548-544daf59-da03-465a-9dd3-f2fe1906c039.png)

**Result page:**
- reduce spacing between all components (remove areas circled in image)
![image](https://user-images.githubusercontent.com/114086037/193406525-886231e9-843f-4549-a31d-21a762117801.png)

**Main Page**
- Remove blue highlight when clicking Geetle logo to play the song.
- When searching a song the search list comes behind the circle player, it should come in front..
![image](https://user-images.githubusercontent.com/114086037/193411963-38e84f1e-38b6-4479-8576-1b5b72891b79.png)

**Comment by chris-lovejoy** [comment]
I think I've fixed the blue highlighting of the geetle logo, as am unable to replicate it - but please check and let me know
